name: Software submission
description: Submit software for review
title: "[Submission]: "
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: submitting-author
    attributes:
      label: Submitting Author
      description: <!--author1-->Name (@github_handle)<!--end-author1-->
      placeholder: <!--author1-->Name (@github_handle)<!--end-author1-->
      value: "Your Full Name (@githubusername)"
    validations:
      required: true
