name: Software submission
description: Submit software for review
title: "[Submission]: "
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: text-area
    id: submitting-author
    attributes:
      label: Submitting Author
      description: Also tell us, what did you expect to happen?
      placeholder: GitHub username
      value: "@githubusername"
    validations:
      required: true
